<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1549247978307" stop="1549247982516">
	<name>Validate the title from home page</name>
	<title>Validate the title from home page</title>
	<test-cases>
		<test-case start="1549247978308" stop="1549247981563" status="passed">
			<name>Enter the correct title</name>
			<title>Enter the correct title</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="0dcfd3c7-aae0-4ecf-a205-8015c9bd2ba0-attachment.png" type="image/png" size="12265"/>
			</attachments>
		</test-case>
		<test-case start="1549247981563" stop="1549247982516" status="failed">
			<name>Enter the incorrect title</name>
			<title>Enter the incorrect title</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="a70e6cab-ea61-4b70-b86b-7e573f760940-attachment.png" type="image/png" size="12265"/>
			</attachments>
			<failure>
				<message>Expected &apos;Protractor practice website - Calculator&apos; to equal &apos;Protractor11 practice website - Calculator&apos;.</message>
				<stack-trace>Error: Failed expectation
    at D:\Projects\Protractor\Basics\AllureValidateTitle.js:34:27
    at ManagedPromise.invokeCallback_ (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>